### PR TITLE
I fixed cors!

### PR DESCRIPTION
**Pull request by Souvlaki42**
Hello I finally fixed cors issue in your npm module. Just merge this request and update npm to use this version. Enjoy!

### CODE REVIEW

**Comment by Souvlaki42** [comment]
Had you look it?

**Comment by AuroPick** [comment]
Hi @Souvlaki42 

Thanks for your contribution

I will get back to you shortly

**Comment by AuroPick** [comment]
Hi @Souvlaki42 

Can you explain how this works?

**Comment by Souvlaki42** [comment]
I tried to pass your api call through a few cors proxies to fix all cors issues some people had with this package.
The current one I used is https://corsproxy.io/. I just changed:
`https://store-site-backend-static.ak.epicgames.com/freeGamesPromotions?country=${country}`
To:
`https://corsproxy.io/?https://store-site-backend-static.ak.epicgames.com/freeGamesPromotions?country=${country}`

**Comment by AuroPick** [comment]
please resolve conflicts.

Waiting your pr to next release.

**Comment by Souvlaki42** [comment]
Sorry for that. You see, I'm new to pull requests. What I have to do to fix those conflicts?

**Comment by AuroPick** [comment]
> Sorry for that. You see, I'm new to pull requests. What I have to do to fix those conflicts?

pull development branch to your local branch resolve conflicts then commit your changes

**Comment by AuroPick** [comment]
this project has been refactored. You need to reimplement your feature.

**Comment by AuroPick** [comment]
@Souvlaki42 if you have any question I can help you.

**Comment by Souvlaki42** [comment]
Yes I actually have a question. I try to console.log the result of the getfreegames function from the epic games class but I get an error saying that console object doesn't exist

**Comment by AuroPick** [comment]
> Yes I actually have a question. I try to console.log the result of the getfreegames function from the epic games class but I get an error saying that console object doesn't exist

please share your code snippet. Did you read new readme: https://github.com/AuroPick/epic-free-games/tree/development#readme

you cant use console log in typescript file firstly you need to build then create a index.js file and run it

it should look like this
```js
const { EpicFreeGames } = require('./dist')

const epicFreeGames = new EpicFreeGames({ country: 'US', locale: 'en-US', includeAll: true })

epicFreeGames.getGames().then(res => console.log(res))
```

**Comment by Souvlaki42** [comment]
I pushed my changes but I don't understand why there are conflicts here. I just added a header and updated some packages with yarn.

**Review by AuroPick — APPROVED** [review]

**Pull request merged**
